### ISSUE TITLE
Instability with the oddschecker() function

### ISSUE THREAD

**Issue by pyroner** [DataWookie/gambleR#1]
the oddschecker() function output when it's run on a valid event, several times, oscillate between beeing the exact same expected output, and displaying this error : "Error in seq.default(6, NA_real_) : 'to' must be a finite number".

This issue became relevant especially when we tried to use the oddschecker() function inside a for loop : the oddschecker() function works fine on the first event (let's call it A) and then for the next event (B), the error occured (exact same previous error), so we ran the oddschecker() function another time on the event B, in a separate call, without modifying anything, it works fine.

**Comment by datawookie** [comment]
Hi!

Thanks for the feedback. This is very odd indeed, but I have looked at your particular event and it seems that there are subtle differences in the HTML that is being returned for some requests (apparently at random). I have made the table parsing code more robust. Please install again and see if the update helps.

Thanks,
Andrew.

**Comment by pyroner** [comment]
Issue resolved !
Thank you so much
